### ISSUE TITLE
handle HTTP / no HTTPS

### ISSUE THREAD

**Issue by Photographix** [JennieJi/vsext-gitlab-snippets#1]
Hello, I run gitlab privately in a docker container. HTTPS and certificates are not important for me. Is it possible that the extension can handle them?

Gitlab workflow for vscode also works without HTTPS, but is too complex for snippets.

`Der Befehl Gitlab Snippets: Add gitlab host hat einen Fehler ausgelöst (request to https://http//gitlab.tier01.intern/api/v4/snippets/public?page=undefined&per_page=undefined failed, reason: getaddrinfo ENOTFOUND http).`

**Comment by JennieJi** [comment]
Thanks @Photographix for feedback! It will take me some time to setup this env, do you mind to try alter the source code and try on your local see whether it works first?

**Comment by Photographix** [comment]
Hello, I have now replaced for me in the `addHost.js,` in line 15 `const PROTOCOL = 'https://'; `with `const PROTOCOL = 'http://';`. So it works for me. Here you might have to add an option for both. But I don't know enough about this. Greetings

**Comment by JennieJi** [comment]
Thanks @Photographix , this is a design fault. I've allowed http in new version v0.0.3 you should be able to update soon.

**Comment by JennieJi** [comment]
https://github.com/JennieJi/vsext-gitlab-snippets/commit/74bc74c9e8a241d0ff7e20fe6761f8eb41474dd1
