### ISSUE TITLE
[BUG] Impossible to see or download my Gitlab snippets

### ISSUE THREAD

**Issue by mf0sse** [JennieJi/vsext-gitlab-snippets#13]
Hello,

I have added my Gitlab account URL as new host and provided a token with API access (I also tried with both api and read_api accesses), then I can see my snippets titles in the "my snippets" section, as intended. But as the title says, when I try to click on any snippet title or "download" icon, I got this message: 
`Lack of token for https://gitlab.com! Please add token and try again.`

The "View in browser" icon works fine anyway.
And I don't know if it matters (I think it doesn't), I installed the extension on VSCodium, not the official VSC.

**Comment by JennieJi** [comment]
🤔Let me try later

**Comment by bingyu50** [comment]
I have the same issue!

**Comment by mf0sse** [comment]
I forgot to mention that, but I solved this some time ago by entering https://gitlab.com instead of https://gitlab.com/userName as gitlab host.
