### ISSUE TITLE
new Access Token

### ISSUE THREAD

**Issue by WebSpectrum** [JennieJi/vsext-gitlab-snippets#18]
i Need to enter a new access token but can't seem to find it in VSCODE settings?

**Comment by JennieJi** [comment]
Hi @WebSpectrum , you may right click the host > choose "remove gitlab host" > and add it again with a new token

**Comment by JennieJi** [comment]
Let's keep this open for adding a new option/command to update token quickly

**Comment by WebSpectrumCode** [comment]
Hi - sorry don't understand, right click where? I do not see this option...

**Comment by WebSpectrumCode** [comment]
Ok - found it - thanks
