### ISSUE TITLE
Typo: Stared should be Starred

### ISSUE THREAD

**Issue by jannismain** [JennieJi/vsext-gitlab-snippets#20]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/14290527/186422945-4eaeda71-2aba-4074-8f9d-e47d538f3b1b.png">

The header of this section should be "Starred" (meaning having stars) and not "Stared" (as in the verb "to stare")

**Comment by JennieJi** [comment]
oops thanks you

**Comment by JennieJi** [comment]
Do you mind to help make a pull request? I am out of PC or laptop recently🫣
