### ISSUE TITLE
Allow publishing of snippets in project

### ISSUE THREAD

**Issue by awoehrl** [JennieJi/vsext-gitlab-snippets#25]
Hi!

Right now it seems all snippets are published directly to the global snippets of the host. However, projects have there own snippets as well and it would be great if we could choose the project to add the snippet.

I've tried using a host path with the project in the URL, but it still added the snippets to the global host.

Cheers
Andreas

**Comment by JennieJi** [comment]
Hi @awoehrl , yes, publishing snippet into project is not considered in the current version.  Would you like to contribute?

To implement this, I think this will need following:
- [x] Add necessary steps in the current publishing prompts for choosing project to publish into
- [ ] Under "MY SNIPPETS" panel, add projects list and list the snippets of the project under each project

To further improve:
- [ ] Add project list in "EXPLORE SNIPPETS" and "STARRED" panels as well
- [ ] Next to each project name in the panels, add a publish button to allow publishing snippets into a project with fewer steps

**Comment by JennieJi** [comment]
Hi @awoehrl , do you have any thoughts on the checklist I mentioned above?
If you are not starting with it, I may start in the upcoming weeks.
